//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     GenTestProject2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    PageStrategy
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using GenTestProject2;

namespace GenTestProject2
{

    /// <summary>
    /// AllComponents - Gauges
    /// </summary>
    public partial interface IAllComponentsGauges
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event SegmentedGauge.Touch (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> SegmentedGauge_TouchEvent;

        /// <summary>
        /// Event Slider.Lower Touch (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Slider_LowerTouchEvent;

        /// <summary>
        /// SegmentedGauge.Touch fb Feedback
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        void SegmentedGauge_Touchfb(short analog);

        /// <summary>
        /// SegmentedGauge.Touch fb Feedback
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        void SegmentedGauge_Touchfb(ushort analog);

        /// <summary>
        /// SegmentedGauge.Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void SegmentedGauge_Touchfb(AllComponentsGaugesUShortInputSigDelegate callback);

        /// <summary>
        /// Slider.Lower Touch fb Feedback
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        void Slider_LowerTouchfb(short analog);

        /// <summary>
        /// Slider.Lower Touch fb Feedback
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        void Slider_LowerTouchfb(ushort analog);

        /// <summary>
        /// Slider.Lower Touch fb Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void Slider_LowerTouchfb(AllComponentsGaugesUShortInputSigDelegate callback);

        /// <summary>
        /// SignalLevelGauge.Signal Value Feedback
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        void SignalLevelGauge_SignalValue(short analog);

        /// <summary>
        /// SignalLevelGauge.Signal Value Feedback
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        void SignalLevelGauge_SignalValue(ushort analog);

        /// <summary>
        /// SignalLevelGauge.Signal Value Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void SignalLevelGauge_SignalValue(AllComponentsGaugesUShortInputSigDelegate callback);

        /// <summary>
        /// WifiSignalLevelGauge.Signal Value Feedback
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        void WifiSignalLevelGauge_SignalValue(short analog);

        /// <summary>
        /// WifiSignalLevelGauge.Signal Value Feedback
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        void WifiSignalLevelGauge_SignalValue(ushort analog);

        /// <summary>
        /// WifiSignalLevelGauge.Signal Value Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void WifiSignalLevelGauge_SignalValue(AllComponentsGaugesUShortInputSigDelegate callback);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="allcomponentsgauges">The <see cref="IAllComponentsGauges"/> on which to apply the feedback.</param>
    public delegate void AllComponentsGaugesUShortInputSigDelegate(UShortInputSig uShortInputSig, IAllComponentsGauges allcomponentsgauges);

    /// <summary>
    /// AllComponents - Gauges
    /// </summary>
    internal partial class AllComponentsGauges : IAllComponentsGauges, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {
                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: AllComponentsGauges.SegmentedGauge.Touch
                /// SegmentedGauge.Touch
                /// </summary>
                public const uint SegmentedGauge_TouchEvent = 3;

                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: AllComponentsGauges.Slider.LowerTouch
                /// Slider.Lower Touch
                /// </summary>
                public const uint Slider_LowerTouchEvent = 4;


                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: AllComponentsGauges.SegmentedGauge.Touchfb
                /// SegmentedGauge.Touch fb
                /// </summary>
                public const uint SegmentedGauge_TouchfbState = 3;

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: AllComponentsGauges.Slider.LowerTouchfb
                /// Slider.Lower Touch fb
                /// </summary>
                public const uint Slider_LowerTouchfbState = 4;

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: AllComponentsGauges.SignalLevelGauge.SignalValue
                /// SignalLevelGauge.Signal Value
                /// </summary>
                public const uint SignalLevelGauge_SignalValueState = 11;

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: AllComponentsGauges.WifiSignalLevelGauge.SignalValue
                /// WifiSignalLevelGauge.Signal Value
                /// </summary>
                public const uint WifiSignalLevelGauge_SignalValueState = 12;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="AllComponentsGauges"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal AllComponentsGauges(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AllComponentsGauges"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal AllComponentsGauges(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="AllComponentsGauges"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.SegmentedGauge_TouchEvent, onSegmentedGauge_Touch);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.Slider_LowerTouchEvent, onSlider_LowerTouch);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> SegmentedGauge_TouchEvent;
        private void onSegmentedGauge_Touch(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = SegmentedGauge_TouchEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Slider_LowerTouchEvent;
        private void onSlider_LowerTouch(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Slider_LowerTouchEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void SegmentedGauge_Touchfb(AllComponentsGaugesUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.SegmentedGauge_TouchfbState], this);
            }
        }

        /// <inheritdoc/>
        public void SegmentedGauge_Touchfb(ushort analog)
        {
            SegmentedGauge_Touchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void SegmentedGauge_Touchfb(short analog)
        {
            SegmentedGauge_Touchfb((sig, component) => sig.ShortValue = analog);
        }
        /// <inheritdoc/>
        public void Slider_LowerTouchfb(AllComponentsGaugesUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.Slider_LowerTouchfbState], this);
            }
        }

        /// <inheritdoc/>
        public void Slider_LowerTouchfb(ushort analog)
        {
            Slider_LowerTouchfb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void Slider_LowerTouchfb(short analog)
        {
            Slider_LowerTouchfb((sig, component) => sig.ShortValue = analog);
        }
        /// <inheritdoc/>
        public void SignalLevelGauge_SignalValue(AllComponentsGaugesUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.SignalLevelGauge_SignalValueState], this);
            }
        }

        /// <inheritdoc/>
        public void SignalLevelGauge_SignalValue(ushort analog)
        {
            SignalLevelGauge_SignalValue((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void SignalLevelGauge_SignalValue(short analog)
        {
            SignalLevelGauge_SignalValue((sig, component) => sig.ShortValue = analog);
        }
        /// <inheritdoc/>
        public void WifiSignalLevelGauge_SignalValue(AllComponentsGaugesUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.WifiSignalLevelGauge_SignalValueState], this);
            }
        }

        /// <inheritdoc/>
        public void WifiSignalLevelGauge_SignalValue(ushort analog)
        {
            WifiSignalLevelGauge_SignalValue((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void WifiSignalLevelGauge_SignalValue(short analog)
        {
            WifiSignalLevelGauge_SignalValue((sig, component) => sig.ShortValue = analog);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "AllComponentsGauges", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            SegmentedGauge_TouchEvent = null;
            Slider_LowerTouchEvent = null;
        }

        #endregion
    }
}
