//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     GenTestProject2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    PageStrategy
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using GenTestProject2;

namespace GenTestProject2
{

    /// <summary>
    /// AllComponents - Text
    /// </summary>
    public partial interface IAllComponentsText
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event Textinput.Output Text (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Textinput_OutputTextEvent;

        /// <summary>
        /// Event ColorChip.Red Value (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ColorChip_RedValueEvent;

        /// <summary>
        /// Event ColorPicker.Red Value (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ColorPicker_RedValueEvent;

        /// <summary>
        /// Event ColorChip.Green Value (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ColorChip_GreenValueEvent;

        /// <summary>
        /// Event ColorPicker.Green Value (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ColorPicker_GreenValueEvent;

        /// <summary>
        /// Event ColorChip.Blue Value (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ColorChip_BlueValueEvent;

        /// <summary>
        /// Event ColorPicker.Blue Value (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ColorPicker_BlueValueEvent;

        /// <summary>
        /// ColorChip.Red Value Feedback
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        void ColorChip_RedValue_fb(short analog);

        /// <summary>
        /// ColorChip.Red Value Feedback
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        void ColorChip_RedValue_fb(ushort analog);

        /// <summary>
        /// ColorChip.Red Value Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void ColorChip_RedValue_fb(AllComponentsTextUShortInputSigDelegate callback);

        /// <summary>
        /// ColorPicker.Red Value Feedback
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        void ColorPicker_RedValue_fb(short analog);

        /// <summary>
        /// ColorPicker.Red Value Feedback
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        void ColorPicker_RedValue_fb(ushort analog);

        /// <summary>
        /// ColorPicker.Red Value Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void ColorPicker_RedValue_fb(AllComponentsTextUShortInputSigDelegate callback);

        /// <summary>
        /// ColorChip.Green Value Feedback
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        void ColorChip_GreenValue_fb(short analog);

        /// <summary>
        /// ColorChip.Green Value Feedback
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        void ColorChip_GreenValue_fb(ushort analog);

        /// <summary>
        /// ColorChip.Green Value Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void ColorChip_GreenValue_fb(AllComponentsTextUShortInputSigDelegate callback);

        /// <summary>
        /// ColorPicker.Green Value Feedback
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        void ColorPicker_GreenValue_fb(short analog);

        /// <summary>
        /// ColorPicker.Green Value Feedback
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        void ColorPicker_GreenValue_fb(ushort analog);

        /// <summary>
        /// ColorPicker.Green Value Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void ColorPicker_GreenValue_fb(AllComponentsTextUShortInputSigDelegate callback);

        /// <summary>
        /// ColorChip.Blue Value Feedback
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        void ColorChip_BlueValue_fb(short analog);

        /// <summary>
        /// ColorChip.Blue Value Feedback
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        void ColorChip_BlueValue_fb(ushort analog);

        /// <summary>
        /// ColorChip.Blue Value Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void ColorChip_BlueValue_fb(AllComponentsTextUShortInputSigDelegate callback);

        /// <summary>
        /// ColorPicker.Blue Value Feedback
        /// </summary>
        /// <param name="analog">The short analog to update the panel.</param>
        void ColorPicker_BlueValue_fb(short analog);

        /// <summary>
        /// ColorPicker.Blue Value Feedback
        /// </summary>
        /// <param name="analog">The ushort analog to update the panel.</param>
        void ColorPicker_BlueValue_fb(ushort analog);

        /// <summary>
        /// ColorPicker.Blue Value Feedback
        /// </summary>
        /// <param name="callback">The ushort delegate to update the panel.</param>
        void ColorPicker_BlueValue_fb(AllComponentsTextUShortInputSigDelegate callback);

        /// <summary>
        /// Textinput.Indirect Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Textinput_IndirectText(string serial);

        /// <summary>
        /// Textinput.Indirect Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Textinput_IndirectText(AllComponentsTextStringInputSigDelegate callback);

        /// <summary>
        /// Text.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void Text_IndirectRichText(string serial);

        /// <summary>
        /// Text.Indirect Rich Text Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void Text_IndirectRichText(AllComponentsTextStringInputSigDelegate callback);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="uShortInputSig">The <see cref="UShortInputSig"/> joinInfo data.</param>
    /// <param name="allcomponentstext">The <see cref="IAllComponentsText"/> on which to apply the feedback.</param>
    public delegate void AllComponentsTextUShortInputSigDelegate(UShortInputSig uShortInputSig, IAllComponentsText allcomponentstext);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="allcomponentstext">The <see cref="IAllComponentsText"/> on which to apply the feedback.</param>
    public delegate void AllComponentsTextStringInputSigDelegate(StringInputSig stringInputSig, IAllComponentsText allcomponentstext);

    /// <summary>
    /// AllComponents - Text
    /// </summary>
    internal partial class AllComponentsText : IAllComponentsText, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Analog signals.
            /// </summary>
            internal static class Numerics
            {
                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: AllComponentsText.ColorChip.RedValue
                /// ColorChip.Red Value
                /// </summary>
                public const uint ColorChip_RedValueEvent = 6;

                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: AllComponentsText.ColorPicker.RedValue
                /// ColorPicker.Red Value
                /// </summary>
                public const uint ColorPicker_RedValueEvent = 7;

                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: AllComponentsText.ColorChip.GreenValue
                /// ColorChip.Green Value
                /// </summary>
                public const uint ColorChip_GreenValueEvent = 8;

                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: AllComponentsText.ColorPicker.GreenValue
                /// ColorPicker.Green Value
                /// </summary>
                public const uint ColorPicker_GreenValueEvent = 9;

                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: AllComponentsText.ColorChip.BlueValue
                /// ColorChip.Blue Value
                /// </summary>
                public const uint ColorChip_BlueValueEvent = 10;

                /// <summary>
                /// Output or Event analog joinInfo from panel to Control System: AllComponentsText.ColorPicker.BlueValue
                /// ColorPicker.Blue Value
                /// </summary>
                public const uint ColorPicker_BlueValueEvent = 11;


                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: AllComponentsText.ColorChip.RedValue_fb
                /// ColorChip.Red Value
                /// </summary>
                public const uint ColorChip_RedValue_fbState = 6;

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: AllComponentsText.ColorPicker.RedValue_fb
                /// ColorPicker.Red Value
                /// </summary>
                public const uint ColorPicker_RedValue_fbState = 7;

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: AllComponentsText.ColorChip.GreenValue_fb
                /// ColorChip.Green Value
                /// </summary>
                public const uint ColorChip_GreenValue_fbState = 8;

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: AllComponentsText.ColorPicker.GreenValue_fb
                /// ColorPicker.Green Value
                /// </summary>
                public const uint ColorPicker_GreenValue_fbState = 9;

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: AllComponentsText.ColorChip.BlueValue_fb
                /// ColorChip.Blue Value
                /// </summary>
                public const uint ColorChip_BlueValue_fbState = 10;

                /// <summary>
                /// Input or Feedback analog joinInfo from Control System to panel: AllComponentsText.ColorPicker.BlueValue_fb
                /// ColorPicker.Blue Value
                /// </summary>
                public const uint ColorPicker_BlueValue_fbState = 11;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {
                /// <summary>
                /// Output or Event serial joinInfo from panel to Control System: AllComponentsText.Textinput.OutputText
                /// Textinput.Output Text
                /// </summary>
                public const uint Textinput_OutputTextEvent = 1;

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: AllComponentsText.Textinput.IndirectText
                /// Textinput.Indirect Text
                /// </summary>
                public const uint Textinput_IndirectTextState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: AllComponentsText.Text.IndirectRichText
                /// Text.Indirect Rich Text
                /// </summary>
                public const uint Text_IndirectRichTextState = 2;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="AllComponentsText"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal AllComponentsText(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AllComponentsText"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal AllComponentsText(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="AllComponentsText"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.ColorChip_RedValueEvent, onColorChip_RedValue);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.ColorPicker_RedValueEvent, onColorPicker_RedValue);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.ColorChip_GreenValueEvent, onColorChip_GreenValue);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.ColorPicker_GreenValueEvent, onColorPicker_GreenValue);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.ColorChip_BlueValueEvent, onColorChip_BlueValue);
            ComponentMediator.ConfigureNumericEvent(controlJoinId, Joins.Numerics.ColorPicker_BlueValueEvent, onColorPicker_BlueValue);
            ComponentMediator.ConfigureStringEvent(controlJoinId, Joins.Strings.Textinput_OutputTextEvent, onTextinput_OutputText);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Textinput_OutputTextEvent;
        private void onTextinput_OutputText(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Textinput_OutputTextEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ColorChip_RedValueEvent;
        private void onColorChip_RedValue(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ColorChip_RedValueEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ColorPicker_RedValueEvent;
        private void onColorPicker_RedValue(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ColorPicker_RedValueEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ColorChip_GreenValueEvent;
        private void onColorChip_GreenValue(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ColorChip_GreenValueEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ColorPicker_GreenValueEvent;
        private void onColorPicker_GreenValue(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ColorPicker_GreenValueEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ColorChip_BlueValueEvent;
        private void onColorChip_BlueValue(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ColorChip_BlueValueEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ColorPicker_BlueValueEvent;
        private void onColorPicker_BlueValue(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ColorPicker_BlueValueEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public void ColorChip_RedValue_fb(AllComponentsTextUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.ColorChip_RedValue_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ColorChip_RedValue_fb(ushort analog)
        {
            ColorChip_RedValue_fb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void ColorChip_RedValue_fb(short analog)
        {
            ColorChip_RedValue_fb((sig, component) => sig.ShortValue = analog);
        }
        /// <inheritdoc/>
        public void ColorPicker_RedValue_fb(AllComponentsTextUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.ColorPicker_RedValue_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ColorPicker_RedValue_fb(ushort analog)
        {
            ColorPicker_RedValue_fb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void ColorPicker_RedValue_fb(short analog)
        {
            ColorPicker_RedValue_fb((sig, component) => sig.ShortValue = analog);
        }
        /// <inheritdoc/>
        public void ColorChip_GreenValue_fb(AllComponentsTextUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.ColorChip_GreenValue_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ColorChip_GreenValue_fb(ushort analog)
        {
            ColorChip_GreenValue_fb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void ColorChip_GreenValue_fb(short analog)
        {
            ColorChip_GreenValue_fb((sig, component) => sig.ShortValue = analog);
        }
        /// <inheritdoc/>
        public void ColorPicker_GreenValue_fb(AllComponentsTextUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.ColorPicker_GreenValue_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ColorPicker_GreenValue_fb(ushort analog)
        {
            ColorPicker_GreenValue_fb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void ColorPicker_GreenValue_fb(short analog)
        {
            ColorPicker_GreenValue_fb((sig, component) => sig.ShortValue = analog);
        }
        /// <inheritdoc/>
        public void ColorChip_BlueValue_fb(AllComponentsTextUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.ColorChip_BlueValue_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ColorChip_BlueValue_fb(ushort analog)
        {
            ColorChip_BlueValue_fb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void ColorChip_BlueValue_fb(short analog)
        {
            ColorChip_BlueValue_fb((sig, component) => sig.ShortValue = analog);
        }
        /// <inheritdoc/>
        public void ColorPicker_BlueValue_fb(AllComponentsTextUShortInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].UShortInput[Joins.Numerics.ColorPicker_BlueValue_fbState], this);
            }
        }

        /// <inheritdoc/>
        public void ColorPicker_BlueValue_fb(ushort analog)
        {
            ColorPicker_BlueValue_fb((sig, component) => sig.UShortValue = analog);
        }

        /// <inheritdoc/>
        public void ColorPicker_BlueValue_fb(short analog)
        {
            ColorPicker_BlueValue_fb((sig, component) => sig.ShortValue = analog);
        }

        /// <inheritdoc/>
        public void Textinput_IndirectText(AllComponentsTextStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Textinput_IndirectTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Textinput_IndirectText(string serial)
        {
            Textinput_IndirectText((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void Text_IndirectRichText(AllComponentsTextStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.Text_IndirectRichTextState], this);
            }
        }

        /// <inheritdoc/>
        public void Text_IndirectRichText(string serial)
        {
            Text_IndirectRichText((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "AllComponentsText", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            Textinput_OutputTextEvent = null;
            ColorChip_RedValueEvent = null;
            ColorPicker_RedValueEvent = null;
            ColorChip_GreenValueEvent = null;
            ColorPicker_GreenValueEvent = null;
            ColorChip_BlueValueEvent = null;
            ColorPicker_BlueValueEvent = null;
        }

        #endregion
    }
}
