//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     GenTestProject2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    PageStrategy
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using GenTestProject2;

namespace GenTestProject2
{

    /// <summary>
    /// ButtonVariants
    /// </summary>
    public partial interface IButtonVariants
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event CheckboxButton.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> CheckboxButton_PressEvent;

        /// <summary>
        /// Event IconButton.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> IconButton_PressEvent;

        /// <summary>
        /// Event ImageButton.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> ImageButton_PressEvent;

        /// <summary>
        /// CheckboxButton.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void CheckboxButton_Selected(bool digital);

        /// <summary>
        /// CheckboxButton.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void CheckboxButton_Selected(ButtonVariantsBoolInputSigDelegate callback);

        /// <summary>
        /// IconButton.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void IconButton_Selected(bool digital);

        /// <summary>
        /// IconButton.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void IconButton_Selected(ButtonVariantsBoolInputSigDelegate callback);

        /// <summary>
        /// ImageButton.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void ImageButton_Selected(bool digital);

        /// <summary>
        /// ImageButton.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void ImageButton_Selected(ButtonVariantsBoolInputSigDelegate callback);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="buttonvariants">The <see cref="IButtonVariants"/> on which to apply the feedback.</param>
    public delegate void ButtonVariantsBoolInputSigDelegate(BoolInputSig boolInputSig, IButtonVariants buttonvariants);

    /// <summary>
    /// ButtonVariants
    /// </summary>
    internal partial class ButtonVariants : IButtonVariants, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ButtonVariants.CheckboxButton.Press
                /// CheckboxButton.Press
                /// </summary>
                public const uint CheckboxButton_PressEvent = 3;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ButtonVariants.IconButton.Press
                /// IconButton.Press
                /// </summary>
                public const uint IconButton_PressEvent = 4;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ButtonVariants.ImageButton.Press
                /// ImageButton.Press
                /// </summary>
                public const uint ImageButton_PressEvent = 5;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ButtonVariants.CheckboxButton.Selected
                /// CheckboxButton.Selected
                /// </summary>
                public const uint CheckboxButton_SelectedState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ButtonVariants.IconButton.Selected
                /// IconButton.Selected
                /// </summary>
                public const uint IconButton_SelectedState = 4;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ButtonVariants.ImageButton.Selected
                /// ImageButton.Selected
                /// </summary>
                public const uint ImageButton_SelectedState = 5;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="ButtonVariants"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal ButtonVariants(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ButtonVariants"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal ButtonVariants(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ButtonVariants"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.CheckboxButton_PressEvent, onCheckboxButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.IconButton_PressEvent, onIconButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.ImageButton_PressEvent, onImageButton_Press);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> CheckboxButton_PressEvent;
        private void onCheckboxButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = CheckboxButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> IconButton_PressEvent;
        private void onIconButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = IconButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> ImageButton_PressEvent;
        private void onImageButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = ImageButton_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }
        /// <inheritdoc/>
        public void CheckboxButton_Selected(ButtonVariantsBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.CheckboxButton_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void CheckboxButton_Selected(bool digital)
        {
            CheckboxButton_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void IconButton_Selected(ButtonVariantsBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.IconButton_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void IconButton_Selected(bool digital)
        {
            IconButton_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void ImageButton_Selected(ButtonVariantsBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.ImageButton_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void ImageButton_Selected(bool digital)
        {
            ImageButton_Selected((sig, component) => sig.BoolValue = digital);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "ButtonVariants", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            CheckboxButton_PressEvent = null;
            IconButton_PressEvent = null;
            ImageButton_PressEvent = null;
        }

        #endregion
    }
}
