//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     GenTestProject2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    Classic
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using System;
using System.Collections.Generic;
using System.Linq;

namespace GenTestProject2
{
    /// <summary>
    /// Common Interface for Root Contracts.
    /// </summary>
    public interface IContract
    {
        object UserObject { get; set; }
        void AddDevice(BasicTriListWithSmartObject device);
        void RemoveDevice(BasicTriListWithSmartObject device);

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        event EventHandler<EventArgs> Activity;
    }

    /// <summary>
    /// Root contract giving access to top level project items such as Pages and global Widgets.
    /// </summary>
    public sealed class Contract : IContract, IDisposable
    {
        #region Components

        private ComponentMediator ComponentMediator { get; set; }

        public GenTestProject2.IButtonVariants ButtonVariants { get { return (GenTestProject2.IButtonVariants)InternalButtonVariants; } }
        private GenTestProject2.ButtonVariants InternalButtonVariants { get; set; }

        public GenTestProject2.AllComponentsButtons.IAllComponentsButtons AllComponentsButtons { get { return (GenTestProject2.AllComponentsButtons.IAllComponentsButtons)InternalAllComponentsButtons; } }
        private GenTestProject2.AllComponentsButtons.AllComponentsButtons InternalAllComponentsButtons { get; set; }

        public GenTestProject2.IAllComponentsGauges AllComponentsGauges { get { return (GenTestProject2.IAllComponentsGauges)InternalAllComponentsGauges; } }
        private GenTestProject2.AllComponentsGauges InternalAllComponentsGauges { get; set; }

        public GenTestProject2.AllComponentsKeypads.IAllComponentsKeypads AllComponentsKeypads { get { return (GenTestProject2.AllComponentsKeypads.IAllComponentsKeypads)InternalAllComponentsKeypads; } }
        private GenTestProject2.AllComponentsKeypads.AllComponentsKeypads InternalAllComponentsKeypads { get; set; }

        public GenTestProject2.AllComponentsMedia.IAllComponentsMedia AllComponentsMedia { get { return (GenTestProject2.AllComponentsMedia.IAllComponentsMedia)InternalAllComponentsMedia; } }
        private GenTestProject2.AllComponentsMedia.AllComponentsMedia InternalAllComponentsMedia { get; set; }

        public GenTestProject2.IAllComponentsText AllComponentsText { get { return (GenTestProject2.IAllComponentsText)InternalAllComponentsText; } }
        private GenTestProject2.AllComponentsText InternalAllComponentsText { get; set; }

        public GenTestProject2.ComplexContracts.IComplexContracts ComplexContracts { get { return (GenTestProject2.ComplexContracts.IComplexContracts)InternalComplexContracts; } }
        private GenTestProject2.ComplexContracts.ComplexContracts InternalComplexContracts { get; set; }

        #endregion

        #region Construction and Initialization

        public Contract()
            : this(new List<BasicTriListWithSmartObject>().ToArray())
        {
        }

        public Contract(BasicTriListWithSmartObject device)
            : this(new [] { device })
        {
        }

        public Contract(BasicTriListWithSmartObject[] devices)
        {
            if (devices == null)
                throw new ArgumentNullException("Devices is null");

            ComponentMediator = new ComponentMediator();
            ComponentMediator.ConfigureActivityEvent(onActivity);

            InternalButtonVariants = new GenTestProject2.ButtonVariants(ComponentMediator, 1);

            InternalAllComponentsButtons = new GenTestProject2.AllComponentsButtons.AllComponentsButtons(ComponentMediator, 4);

            InternalAllComponentsGauges = new GenTestProject2.AllComponentsGauges(ComponentMediator, 7);

            InternalAllComponentsKeypads = new GenTestProject2.AllComponentsKeypads.AllComponentsKeypads(ComponentMediator, 8);

            InternalAllComponentsMedia = new GenTestProject2.AllComponentsMedia.AllComponentsMedia(ComponentMediator, 11);

            InternalAllComponentsText = new GenTestProject2.AllComponentsText(ComponentMediator, 14);

            InternalComplexContracts = new GenTestProject2.ComplexContracts.ComplexContracts(ComponentMediator, 15);


            for (int index = 0; index < devices.Length; index++)
            {
                AddDevice(devices[index]);
            }
        }

        /// <summary>
        /// Fires on ANY activity on the panel.
        /// </summary>
        public event EventHandler<EventArgs> Activity;
        private void onActivity(GenericBase currentDevice, SmartObjectEventArgs args)
        {
            var handler = Activity;
            if (handler != null)
                handler(currentDevice, args);
        }
        #endregion

        #region Standard Contract Members

        public object UserObject { get; set; }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            InternalButtonVariants.AddDevice(device);
            InternalAllComponentsButtons.AddDevice(device);
            InternalAllComponentsGauges.AddDevice(device);
            InternalAllComponentsKeypads.AddDevice(device);
            InternalAllComponentsMedia.AddDevice(device);
            InternalAllComponentsText.AddDevice(device);
            InternalComplexContracts.AddDevice(device);

        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            InternalButtonVariants.RemoveDevice(device);
            InternalAllComponentsButtons.RemoveDevice(device);
            InternalAllComponentsGauges.RemoveDevice(device);
            InternalAllComponentsKeypads.RemoveDevice(device);
            InternalAllComponentsMedia.RemoveDevice(device);
            InternalAllComponentsText.RemoveDevice(device);
            InternalComplexContracts.RemoveDevice(device);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            InternalButtonVariants.Dispose();
            InternalAllComponentsButtons.Dispose();
            InternalAllComponentsGauges.Dispose();
            InternalAllComponentsKeypads.Dispose();
            InternalAllComponentsMedia.Dispose();
            InternalAllComponentsText.Dispose();
            InternalComplexContracts.Dispose();

            ComponentMediator.Dispose(); 
        }

        #endregion
    }
}

