//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     GenTestProject2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    MediaPlayerStrategy
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using GenTestProject2;

namespace GenTestProject2.AllComponentsMedia
{

    /// <summary>
    /// MediaPlayer
    /// </summary>
    public partial interface IMediaPlayer
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event MediaPlayer.CRPC (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> MediaPlayer_CRPCEvent;

        /// <summary>
        /// MediaPlayer.Refresh Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void MediaPlayer_Refresh(bool digital);

        /// <summary>
        /// MediaPlayer.Refresh Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void MediaPlayer_Refresh(MediaPlayerBoolInputSigDelegate callback);

        /// <summary>
        /// MediaPlayer.Offline Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void MediaPlayer_Offline(bool digital);

        /// <summary>
        /// MediaPlayer.Offline Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void MediaPlayer_Offline(MediaPlayerBoolInputSigDelegate callback);

        /// <summary>
        /// MediaPlayer.CRPC_FB Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void MediaPlayer_CRPC_FB(string serial);

        /// <summary>
        /// MediaPlayer.CRPC_FB Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void MediaPlayer_CRPC_FB(MediaPlayerStringInputSigDelegate callback);

        /// <summary>
        /// MediaPlayer.Player_Name Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void MediaPlayer_Player_Name(string serial);

        /// <summary>
        /// MediaPlayer.Player_Name Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void MediaPlayer_Player_Name(MediaPlayerStringInputSigDelegate callback);

        /// <summary>
        /// MediaPlayer.Message_FB Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void MediaPlayer_Message_FB(string serial);

        /// <summary>
        /// MediaPlayer.Message_FB Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void MediaPlayer_Message_FB(MediaPlayerStringInputSigDelegate callback);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="mediaplayer">The <see cref="IMediaPlayer"/> on which to apply the feedback.</param>
    public delegate void MediaPlayerBoolInputSigDelegate(BoolInputSig boolInputSig, IMediaPlayer mediaplayer);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="mediaplayer">The <see cref="IMediaPlayer"/> on which to apply the feedback.</param>
    public delegate void MediaPlayerStringInputSigDelegate(StringInputSig stringInputSig, IMediaPlayer mediaplayer);

    /// <summary>
    /// MediaPlayer
    /// </summary>
    internal partial class MediaPlayer : IMediaPlayer, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: AllComponentsMedia.MediaPlayer.Refresh
                /// MediaPlayer.Refresh
                /// </summary>
                public const uint MediaPlayer_RefreshState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: AllComponentsMedia.MediaPlayer.Offline
                /// MediaPlayer.Offline
                /// </summary>
                public const uint MediaPlayer_OfflineState = 2;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {
                /// <summary>
                /// Output or Event serial joinInfo from panel to Control System: AllComponentsMedia.MediaPlayer.CRPC
                /// MediaPlayer.CRPC
                /// </summary>
                public const uint MediaPlayer_CRPCEvent = 1;

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: AllComponentsMedia.MediaPlayer.CRPC_FB
                /// MediaPlayer.CRPC_FB
                /// </summary>
                public const uint MediaPlayer_CRPC_FBState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: AllComponentsMedia.MediaPlayer.Player_Name
                /// MediaPlayer.Player_Name
                /// </summary>
                public const uint MediaPlayer_Player_NameState = 2;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: AllComponentsMedia.MediaPlayer.Message_FB
                /// MediaPlayer.Message_FB
                /// </summary>
                public const uint MediaPlayer_Message_FBState = 3;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaPlayer"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal MediaPlayer(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaPlayer"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal MediaPlayer(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaPlayer"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureStringEvent(controlJoinId, Joins.Strings.MediaPlayer_CRPCEvent, onMediaPlayer_CRPC);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> MediaPlayer_CRPCEvent;
        private void onMediaPlayer_CRPC(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = MediaPlayer_CRPCEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }
        /// <inheritdoc/>
        public void MediaPlayer_Refresh(MediaPlayerBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.MediaPlayer_RefreshState], this);
            }
        }

        /// <inheritdoc/>
        public void MediaPlayer_Refresh(bool digital)
        {
            MediaPlayer_Refresh((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void MediaPlayer_Offline(MediaPlayerBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.MediaPlayer_OfflineState], this);
            }
        }

        /// <inheritdoc/>
        public void MediaPlayer_Offline(bool digital)
        {
            MediaPlayer_Offline((sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void MediaPlayer_CRPC_FB(MediaPlayerStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.MediaPlayer_CRPC_FBState], this);
            }
        }

        /// <inheritdoc/>
        public void MediaPlayer_CRPC_FB(string serial)
        {
            MediaPlayer_CRPC_FB((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void MediaPlayer_Player_Name(MediaPlayerStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.MediaPlayer_Player_NameState], this);
            }
        }

        /// <inheritdoc/>
        public void MediaPlayer_Player_Name(string serial)
        {
            MediaPlayer_Player_Name((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void MediaPlayer_Message_FB(MediaPlayerStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.MediaPlayer_Message_FBState], this);
            }
        }

        /// <inheritdoc/>
        public void MediaPlayer_Message_FB(string serial)
        {
            MediaPlayer_Message_FB((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "MediaPlayer", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            MediaPlayer_CRPCEvent = null;
        }

        #endregion
    }
}
