//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     GenTestProject2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    ButtonListStrategy
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using GenTestProject2;

namespace GenTestProject2.ComplexContracts
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IButtonListThemeByItem
    {
        /// <summary>
        /// Fires on button list presses.  Event carries <see="IndexedButtonEventArgs"/> with ButtonIndex property (0 based).
        /// </summary>
        event EventHandler<IndexedButtonEventArgs> Button_PressEvent;

        /// <summary>
        /// Helper Button1.ItemSelected Feedback
        /// </summary>
        /// <param name="buttonIndex"">The index of the button (0 based).</param>
        /// <param name="digital">The <see="bool"/> value to set on the panel.</param>
        void Button_Selected(ushort buttonIndex, bool digital);

        /// <summary>
        /// Button1.ItemSelected Feedback
        /// </summary>
        /// <param name="buttonIndex">The index of the button (0 based).</param>
        /// <param name="callback">The bool delegate to set the feedback.</param>
        void Button_Selected(ushort buttonIndex, ButtonListThemeBoolInputSigDelegate callback);
    }


    /// <summary>
    /// Search List
    /// </summary>
    internal partial class ButtonListTheme
    {
        #region CH5 Contract
        /// <inheritdoc/>
        public event EventHandler<IndexedButtonEventArgs> Button_PressEvent;
        private void onButton_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<IndexedButtonEventArgs> handler = Button_PressEvent;
            if (handler != null)
                handler(this, new IndexedButtonEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, eventArgs.JoinIndex));
        }
                

        /// <inheritdoc/>
        public void Button_Selected(ushort buttonIndex, bool digital)
        {
            Button_Selected(buttonIndex, (sig, component) => sig.BoolValue = digital);
        }

        /// <inheritdoc/>
        public void Button_Selected(ushort buttonIndex, ButtonListThemeBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_1_Button_SelectedState + (uint)buttonIndex * 1], this);
            }
        }

        #endregion
    }

    /// <summary>
    /// ButtonListTheme
    /// </summary>
    public partial interface IButtonListTheme : IButtonListThemeByItem
    {
        object UserObject { get; set; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="buttonlisttheme">The <see cref="IButtonListTheme"/> on which to apply the feedback.</param>
    public delegate void ButtonListThemeBoolInputSigDelegate(BoolInputSig boolInputSig, IButtonListTheme buttonlisttheme);

    /// <summary>
    /// ButtonListTheme
    /// </summary>
    internal partial class ButtonListTheme : IButtonListTheme, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.ButtonListTheme.Button1ItemPress
                /// Button1.ItemPress
                /// </summary>
                public const uint Button_1_Button_PressEvent = 1001;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.ButtonListTheme.Button2ItemPress
                /// Button2.ItemPress
                /// </summary>
                public const uint Button_2_Button_PressEvent = 1002;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.ButtonListTheme.Button3ItemPress
                /// Button3.ItemPress
                /// </summary>
                public const uint Button_3_Button_PressEvent = 1003;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.ButtonListTheme.Button4ItemPress
                /// Button4.ItemPress
                /// </summary>
                public const uint Button_4_Button_PressEvent = 1004;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.ButtonListTheme.Button5ItemPress
                /// Button5.ItemPress
                /// </summary>
                public const uint Button_5_Button_PressEvent = 1005;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.ButtonListTheme.Button6ItemPress
                /// Button6.ItemPress
                /// </summary>
                public const uint Button_6_Button_PressEvent = 1006;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.ButtonListTheme.Button7ItemPress
                /// Button7.ItemPress
                /// </summary>
                public const uint Button_7_Button_PressEvent = 1007;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.ButtonListTheme.Button8ItemPress
                /// Button8.ItemPress
                /// </summary>
                public const uint Button_8_Button_PressEvent = 1008;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.ButtonListTheme.Button9ItemPress
                /// Button9.ItemPress
                /// </summary>
                public const uint Button_9_Button_PressEvent = 1009;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.ButtonListTheme.Button10ItemPress
                /// Button10.ItemPress
                /// </summary>
                public const uint Button_10_Button_PressEvent = 1010;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.ButtonListTheme.Button1ItemSelected
                /// Button1.ItemSelected
                /// </summary>
                public const uint Button_1_Button_SelectedState = 1001;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.ButtonListTheme.Button2ItemSelected
                /// Button2.ItemSelected
                /// </summary>
                public const uint Button_2_Button_SelectedState = 1002;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.ButtonListTheme.Button3ItemSelected
                /// Button3.ItemSelected
                /// </summary>
                public const uint Button_3_Button_SelectedState = 1003;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.ButtonListTheme.Button4ItemSelected
                /// Button4.ItemSelected
                /// </summary>
                public const uint Button_4_Button_SelectedState = 1004;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.ButtonListTheme.Button5ItemSelected
                /// Button5.ItemSelected
                /// </summary>
                public const uint Button_5_Button_SelectedState = 1005;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.ButtonListTheme.Button6ItemSelected
                /// Button6.ItemSelected
                /// </summary>
                public const uint Button_6_Button_SelectedState = 1006;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.ButtonListTheme.Button7ItemSelected
                /// Button7.ItemSelected
                /// </summary>
                public const uint Button_7_Button_SelectedState = 1007;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.ButtonListTheme.Button8ItemSelected
                /// Button8.ItemSelected
                /// </summary>
                public const uint Button_8_Button_SelectedState = 1008;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.ButtonListTheme.Button9ItemSelected
                /// Button9.ItemSelected
                /// </summary>
                public const uint Button_9_Button_SelectedState = 1009;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.ButtonListTheme.Button10ItemSelected
                /// Button10.ItemSelected
                /// </summary>
                public const uint Button_10_Button_SelectedState = 1010;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="ButtonListTheme"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal ButtonListTheme(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ButtonListTheme"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal ButtonListTheme(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ButtonListTheme"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>();
 
            ComponentMediator.ConfigureBooleanItemEvent(controlJoinId, Joins.Booleans.Button_1_Button_PressEvent, GetIndexes, onButton_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            if (controlJoinId == ControlJoinId &&
                join >= Joins.Booleans.Button_1_Button_PressEvent &&
                join <= Joins.Booleans.Button_10_Button_PressEvent)
            {
                return new Indexes(0, (ushort)(join - Joins.Booleans.Button_1_Button_PressEvent), false);
            }

            return new Indexes(0, 0, true);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract


        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "ButtonListTheme", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            Button_PressEvent = null;
        }

        #endregion
    }
}
