//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     GenTestProject2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    PageStrategy
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using GenTestProject2;

namespace GenTestProject2.ComplexContracts
{

    /// <summary>
    /// ComplexContracts
    /// </summary>
    public partial interface IComplexContracts
    {
        object UserObject { get; set; }

        /// <summary>
        /// ComplexComponent DpadTheme
        /// </summary>
        GenTestProject2.ComplexContracts.IDpadTheme DpadTheme { get; }

        /// <summary>
        /// ComplexComponent KeypadTheme
        /// </summary>
        GenTestProject2.ComplexContracts.IKeypadTheme KeypadTheme { get; }

        /// <summary>
        /// ComplexComponent ButtonListTheme
        /// </summary>
        GenTestProject2.ComplexContracts.IButtonListTheme ButtonListTheme { get; }

        /// <summary>
        /// ComplexComponent TabButtonSlide
        /// </summary>
        GenTestProject2.ComplexContracts.ITabButtonSlide TabButtonSlide { get; }

        /// <summary>
        /// ComplexComponent MediaPlayerTheme
        /// </summary>
        GenTestProject2.ComplexContracts.IMediaPlayerTheme MediaPlayerTheme { get; }
    }


    /// <summary>
    /// ComplexContracts
    /// </summary>
    internal partial class ComplexContracts : IComplexContracts, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="ComplexContracts"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal ComplexContracts(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ComplexContracts"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal ComplexContracts(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ComplexContracts"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            DpadTheme = new GenTestProject2.ComplexContracts.DpadTheme(ComponentMediator, 16);
            KeypadTheme = new GenTestProject2.ComplexContracts.KeypadTheme(ComponentMediator, 17);
            ButtonListTheme = new GenTestProject2.ComplexContracts.ButtonListTheme(ComponentMediator, 18);
            TabButtonSlide = new GenTestProject2.ComplexContracts.TabButtonSlide(ComponentMediator, 19);
            MediaPlayerTheme = new GenTestProject2.ComplexContracts.MediaPlayerTheme(ComponentMediator, 20);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((GenTestProject2.ComplexContracts.DpadTheme)DpadTheme).AddDevice(device);

            ((GenTestProject2.ComplexContracts.KeypadTheme)KeypadTheme).AddDevice(device);

            ((GenTestProject2.ComplexContracts.ButtonListTheme)ButtonListTheme).AddDevice(device);

            ((GenTestProject2.ComplexContracts.TabButtonSlide)TabButtonSlide).AddDevice(device);

            ((GenTestProject2.ComplexContracts.MediaPlayerTheme)MediaPlayerTheme).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

        ((GenTestProject2.ComplexContracts.DpadTheme)DpadTheme).RemoveDevice(device);

        ((GenTestProject2.ComplexContracts.KeypadTheme)KeypadTheme).RemoveDevice(device);

        ((GenTestProject2.ComplexContracts.ButtonListTheme)ButtonListTheme).RemoveDevice(device);

        ((GenTestProject2.ComplexContracts.TabButtonSlide)TabButtonSlide).RemoveDevice(device);

        ((GenTestProject2.ComplexContracts.MediaPlayerTheme)MediaPlayerTheme).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <summary>
        /// ComplexComponent DpadTheme
        /// </summary>
        public GenTestProject2.ComplexContracts.IDpadTheme DpadTheme { get; private set; }

        /// <summary>
        /// ComplexComponent KeypadTheme
        /// </summary>
        public GenTestProject2.ComplexContracts.IKeypadTheme KeypadTheme { get; private set; }

        /// <summary>
        /// ComplexComponent ButtonListTheme
        /// </summary>
        public GenTestProject2.ComplexContracts.IButtonListTheme ButtonListTheme { get; private set; }

        /// <summary>
        /// ComplexComponent TabButtonSlide
        /// </summary>
        public GenTestProject2.ComplexContracts.ITabButtonSlide TabButtonSlide { get; private set; }

        /// <summary>
        /// ComplexComponent MediaPlayerTheme
        /// </summary>
        public GenTestProject2.ComplexContracts.IMediaPlayerTheme MediaPlayerTheme { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "ComplexContracts", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

        }

        #endregion
    }
}
