//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     GenTestProject2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    KeypadStrategy
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using GenTestProject2;

namespace GenTestProject2.ComplexContracts
{

    /// <summary>
    /// Allow events by list item and states (feedbacks) to be set by item index.
    /// </summary>
    public partial interface IKeypadThemeByItem
    {
        /// <summary>
        /// Fires on keypad button presses.  Event carries <see="KeypadEventArgs"/> with KeypadButton property of <see="KeypadButton"/> enum type.
        /// </summary>
        event EventHandler<KeypadEventArgs> Button_PressEvent;
    }


    /// <summary>
    /// Keypad instance KeypadTheme.
    /// </summary>
    internal partial class KeypadTheme
    {
        #region CH5 Keypad Contract
        /// <inheritdoc/>
        public event EventHandler<KeypadEventArgs> Button_PressEvent;
        private void onButton_Press(IndexedEventArgs eventArgs)
        {
            EventHandler<KeypadEventArgs> handler = Button_PressEvent;
            if (handler != null)
                handler(this, new KeypadEventArgs((SmartObjectEventArgs)eventArgs.SigArgs, (KeypadButton)eventArgs.JoinIndex));
        }


        #endregion
    }

    /// <summary>
    /// KeypadTheme
    /// </summary>
    public partial interface IKeypadTheme : IKeypadThemeByItem
    {
        object UserObject { get; set; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="keypadtheme">The <see cref="IKeypadTheme"/> on which to apply the feedback.</param>
    public delegate void KeypadThemeBoolInputSigDelegate(BoolInputSig boolInputSig, IKeypadTheme keypadtheme);

    /// <summary>
    /// KeypadTheme
    /// </summary>
    internal partial class KeypadTheme : IKeypadTheme, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.Press1
                /// Press1.Press
                /// </summary>
                public const uint Press1Event = 3;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.Press2
                /// Press2.Press
                /// </summary>
                public const uint Press2Event = 4;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.Press3
                /// Press3.Press
                /// </summary>
                public const uint Press3Event = 5;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.Press4
                /// Press4.Press
                /// </summary>
                public const uint Press4Event = 6;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.Press5
                /// Press5.Press
                /// </summary>
                public const uint Press5Event = 7;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.Press6
                /// Press6.Press
                /// </summary>
                public const uint Press6Event = 8;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.Press7
                /// Press7.Press
                /// </summary>
                public const uint Press7Event = 9;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.Press8
                /// Press8.Press
                /// </summary>
                public const uint Press8Event = 10;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.Press9
                /// Press9.Press
                /// </summary>
                public const uint Press9Event = 11;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.Press0
                /// Press0.Press
                /// </summary>
                public const uint Press0Event = 12;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.PressStar
                /// PressStar.Press
                /// </summary>
                public const uint PressStarEvent = 13;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.PressHash
                /// PressHash.Press
                /// </summary>
                public const uint PressHashEvent = 14;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: ComplexContracts.KeypadTheme.PressExtraButton
                /// PressExtraButton.Press
                /// </summary>
                public const uint PressExtraButtonEvent = 15;


            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="KeypadTheme"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal KeypadTheme(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeypadTheme"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal KeypadTheme(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="KeypadTheme"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanItemEvent(controlJoinId, Joins.Booleans.Press1Event, GetIndexes, onButton_Press);
        }

        /// <summary>
        /// Get the offset when using indexed complex components.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId of the component.</param>
        /// <param name="join">The join offset.</param>
        /// <param name="eSigType">The join data type.</param>
        private Indexes GetIndexes(uint controlJoinId, uint join, eSigType eSigType)
        {
            if (controlJoinId == ControlJoinId &&
                join >= Joins.Booleans.Press1Event &&
                join <= Joins.Booleans.PressExtraButtonEvent)
            {
                return new Indexes(0, (ushort)(join - Joins.Booleans.Press1Event), false);
            }

            return new Indexes(0, 0, true);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract


        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "KeypadTheme", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            Button_PressEvent = null;
        }

        #endregion
    }
}
