//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     GenTestProject2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    MediaPlayerStrategy
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using GenTestProject2;

namespace GenTestProject2.ComplexContracts
{

    /// <summary>
    /// MediaPlayerTheme
    /// </summary>
    public partial interface IMediaPlayerTheme
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event MediaPlayerTheme.CRPC (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> MediaPlayerTheme_CRPCEvent;

        /// <summary>
        /// MediaPlayerTheme.Refresh Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void MediaPlayerTheme_Refresh(bool digital);

        /// <summary>
        /// MediaPlayerTheme.Refresh Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void MediaPlayerTheme_Refresh(MediaPlayerThemeBoolInputSigDelegate callback);

        /// <summary>
        /// MediaPlayerTheme.Offline Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void MediaPlayerTheme_Offline(bool digital);

        /// <summary>
        /// MediaPlayerTheme.Offline Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void MediaPlayerTheme_Offline(MediaPlayerThemeBoolInputSigDelegate callback);

        /// <summary>
        /// MediaPlayerTheme.CRPC_FB Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void MediaPlayerTheme_CRPC_FB(string serial);

        /// <summary>
        /// MediaPlayerTheme.CRPC_FB Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void MediaPlayerTheme_CRPC_FB(MediaPlayerThemeStringInputSigDelegate callback);

        /// <summary>
        /// MediaPlayerTheme.Player_Name Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void MediaPlayerTheme_Player_Name(string serial);

        /// <summary>
        /// MediaPlayerTheme.Player_Name Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void MediaPlayerTheme_Player_Name(MediaPlayerThemeStringInputSigDelegate callback);

        /// <summary>
        /// MediaPlayerTheme.Message_FB Feedback
        /// </summary>
        /// <param name="serial">The <see cref="string"/> to update the panel.</param>
        void MediaPlayerTheme_Message_FB(string serial);

        /// <summary>
        /// MediaPlayerTheme.Message_FB Feedback
        /// </summary>
        /// <param name="callback">The <see cref="string"/> delegate to update the panel.</param>
        void MediaPlayerTheme_Message_FB(MediaPlayerThemeStringInputSigDelegate callback);
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="mediaplayertheme">The <see cref="IMediaPlayerTheme"/> on which to apply the feedback.</param>
    public delegate void MediaPlayerThemeBoolInputSigDelegate(BoolInputSig boolInputSig, IMediaPlayerTheme mediaplayertheme);
    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="stringInputSig">The <see cref="StringInputSig"/> joinInfo data.</param>
    /// <param name="mediaplayertheme">The <see cref="IMediaPlayerTheme"/> on which to apply the feedback.</param>
    public delegate void MediaPlayerThemeStringInputSigDelegate(StringInputSig stringInputSig, IMediaPlayerTheme mediaplayertheme);

    /// <summary>
    /// MediaPlayerTheme
    /// </summary>
    internal partial class MediaPlayerTheme : IMediaPlayerTheme, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.MediaPlayerTheme.Refresh
                /// MediaPlayerTheme.Refresh
                /// </summary>
                public const uint MediaPlayerTheme_RefreshState = 1;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: ComplexContracts.MediaPlayerTheme.Offline
                /// MediaPlayerTheme.Offline
                /// </summary>
                public const uint MediaPlayerTheme_OfflineState = 2;

            }
            /// <summary>
            /// Serial signals.
            /// </summary>
            internal static class Strings
            {
                /// <summary>
                /// Output or Event serial joinInfo from panel to Control System: ComplexContracts.MediaPlayerTheme.CRPC
                /// MediaPlayerTheme.CRPC
                /// </summary>
                public const uint MediaPlayerTheme_CRPCEvent = 1;

                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: ComplexContracts.MediaPlayerTheme.CRPC_FB
                /// MediaPlayerTheme.CRPC_FB
                /// </summary>
                public const uint MediaPlayerTheme_CRPC_FBState = 1;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: ComplexContracts.MediaPlayerTheme.Player_Name
                /// MediaPlayerTheme.Player_Name
                /// </summary>
                public const uint MediaPlayerTheme_Player_NameState = 2;
                /// <summary>
                /// Input or Feedback serial joinInfo from Control System to panel: ComplexContracts.MediaPlayerTheme.Message_FB
                /// MediaPlayerTheme.Message_FB
                /// </summary>
                public const uint MediaPlayerTheme_Message_FBState = 3;
            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaPlayerTheme"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal MediaPlayerTheme(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaPlayerTheme"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal MediaPlayerTheme(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaPlayerTheme"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureStringEvent(controlJoinId, Joins.Strings.MediaPlayerTheme_CRPCEvent, onMediaPlayerTheme_CRPC);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> MediaPlayerTheme_CRPCEvent;
        private void onMediaPlayerTheme_CRPC(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = MediaPlayerTheme_CRPCEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }
        /// <inheritdoc/>
        public void MediaPlayerTheme_Refresh(MediaPlayerThemeBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.MediaPlayerTheme_RefreshState], this);
            }
        }

        /// <inheritdoc/>
        public void MediaPlayerTheme_Refresh(bool digital)
        {
            MediaPlayerTheme_Refresh((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void MediaPlayerTheme_Offline(MediaPlayerThemeBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.MediaPlayerTheme_OfflineState], this);
            }
        }

        /// <inheritdoc/>
        public void MediaPlayerTheme_Offline(bool digital)
        {
            MediaPlayerTheme_Offline((sig, component) => sig.BoolValue = digital);
        }


        /// <inheritdoc/>
        public void MediaPlayerTheme_CRPC_FB(MediaPlayerThemeStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.MediaPlayerTheme_CRPC_FBState], this);
            }
        }

        /// <inheritdoc/>
        public void MediaPlayerTheme_CRPC_FB(string serial)
        {
            MediaPlayerTheme_CRPC_FB((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void MediaPlayerTheme_Player_Name(MediaPlayerThemeStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.MediaPlayerTheme_Player_NameState], this);
            }
        }

        /// <inheritdoc/>
        public void MediaPlayerTheme_Player_Name(string serial)
        {
            MediaPlayerTheme_Player_Name((sig, component) => sig.StringValue = serial);
        }
        /// <inheritdoc/>
        public void MediaPlayerTheme_Message_FB(MediaPlayerThemeStringInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].StringInput[Joins.Strings.MediaPlayerTheme_Message_FBState], this);
            }
        }

        /// <inheritdoc/>
        public void MediaPlayerTheme_Message_FB(string serial)
        {
            MediaPlayerTheme_Message_FB((sig, component) => sig.StringValue = serial);
        }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "MediaPlayerTheme", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            MediaPlayerTheme_CRPCEvent = null;
        }

        #endregion
    }
}
