//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by CrestronConstruct.
//     AppHost:     2.1501.15.0
//     UI Plugin:   1.4801.18.0
//
//     Project:     GenTestProject2
//     Version:     1.0.0.0
//     Sdk:         CH5:2.18.0
//     Strategy:    PageStrategy
//     IndexOnly:   True
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Crestron.SimplSharp;
using Crestron.SimplSharpPro;
using Crestron.SimplSharpPro.DeviceSupport;
using GenTestProject2;

namespace GenTestProject2.AllComponentsButtons
{

    /// <summary>
    /// AllComponents - Buttons
    /// </summary>
    public partial interface IAllComponentsButtons
    {
        object UserObject { get; set; }

        /// <summary>
        /// Event Button.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Button_PressEvent;

        /// <summary>
        /// Event Toggle.Press (from panel to Control System)
        /// </summary>
        event EventHandler<UIEventArgs> Toggle_PressEvent;

        /// <summary>
        /// Button.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Button_Selected(bool digital);

        /// <summary>
        /// Button.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Button_Selected(AllComponentsButtonsBoolInputSigDelegate callback);

        /// <summary>
        /// Toggle.Selected Feedback
        /// </summary>
        /// <param name="digital">The bool to update the panel.</param>
        void Toggle_Selected(bool digital);

        /// <summary>
        /// Toggle.Selected Feedback
        /// </summary>
        /// <param name="callback">The bool delegate to update the panel.</param>
        void Toggle_Selected(AllComponentsButtonsBoolInputSigDelegate callback);

        /// <summary>
        /// ComplexComponent TabButton
        /// </summary>
        GenTestProject2.AllComponentsButtons.ITabButton TabButton { get; }

        /// <summary>
        /// ComplexComponent ButtonList
        /// </summary>
        GenTestProject2.AllComponentsButtons.IButtonList ButtonList { get; }
    }

    /// <summary>
    /// Digital callback used in feedback events.
    /// </summary>
    /// <param name="boolInputSig">The <see cref="BoolInputSig"/> joinInfo data.</param>
    /// <param name="allcomponentsbuttons">The <see cref="IAllComponentsButtons"/> on which to apply the feedback.</param>
    public delegate void AllComponentsButtonsBoolInputSigDelegate(BoolInputSig boolInputSig, IAllComponentsButtons allcomponentsbuttons);

    /// <summary>
    /// AllComponents - Buttons
    /// </summary>
    internal partial class AllComponentsButtons : IAllComponentsButtons, IDisposable
    {
        #region Standard CH5 Component members

        private ComponentMediator ComponentMediator { get; set; }

        public object UserObject { get; set; }

        /// <summary>
        /// Gets the ControlJoinId a.k.a. SmartObjectId.  This Id identifies the extender symbol.
        /// </summary>
        public uint ControlJoinId { get; private set; }

        private IList<BasicTriListWithSmartObject> _devices;

        /// <summary>
        /// Gets the list of devices.
        /// </summary>
        public IList<BasicTriListWithSmartObject> Devices { get { return _devices; } }

        #endregion

        #region Joins

        private static class Joins
        {
            /// <summary>
            /// Digital signals,
            /// </summary>
            internal static class Booleans
            {
                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: AllComponentsButtons.Button.Press
                /// Button.Press
                /// </summary>
                public const uint Button_PressEvent = 3;

                /// <summary>
                /// Output or Event digital joinInfo from panel to Control System: AllComponentsButtons.Toggle.Press
                /// Toggle.Press
                /// </summary>
                public const uint Toggle_PressEvent = 4;


                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: AllComponentsButtons.Button.Selected
                /// Button.Selected
                /// </summary>
                public const uint Button_SelectedState = 3;

                /// <summary>
                /// Input or Feedback digital joinInfo from Control System to panel: AllComponentsButtons.Toggle.Selected
                /// Toggle.Selected
                /// </summary>
                public const uint Toggle_SelectedState = 4;

            }
        }

        #endregion

        #region Construction and Initialization

        /// <summary>
        /// Initializes a new instance of the <see cref="AllComponentsButtons"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        internal AllComponentsButtons(ComponentMediator componentMediator, uint controlJoinId, uint? itemCount)
        {
            ComponentMediator = componentMediator;
            Initialize(controlJoinId, itemCount);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AllComponentsButtons"/> component class.
        /// </summary>
        /// <param name="componentMediator">The <see cref="ComponentMediator"/> used to instantiate the component.</param>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        internal AllComponentsButtons(ComponentMediator componentMediator, uint controlJoinId) : this(componentMediator, controlJoinId, null)
        {
        }

        /// <summary>
        /// Initializes a new instance with default itemCount.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        private void Initialize(uint controlJoinId)
        {
            Initialize(controlJoinId, null);
        }

        private Dictionary<string, Indexes> _indexLookup = new Dictionary<string, Indexes>();

        /// <summary>
        /// Initializes a new instance of the <see cref="AllComponentsButtons"/> component class.
        /// </summary>
        /// <param name="controlJoinId">The SmartObjectId at which to create the component.</param>
        /// <param name="itemCount">The number of items.</param>
        private void Initialize(uint controlJoinId, uint? itemCount)
        {
            ControlJoinId = controlJoinId; 
 
            _devices = new List<BasicTriListWithSmartObject>(); 
 
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Button_PressEvent, onButton_Press);
            ComponentMediator.ConfigureBooleanEvent(controlJoinId, Joins.Booleans.Toggle_PressEvent, onToggle_Press);
            TabButton = new GenTestProject2.AllComponentsButtons.TabButton(ComponentMediator, 5);
            ButtonList = new GenTestProject2.AllComponentsButtons.ButtonList(ComponentMediator, 6);
        }

        public void AddDevice(BasicTriListWithSmartObject device)
        {
            Devices.Add(device);
            ComponentMediator.HookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

            ((GenTestProject2.AllComponentsButtons.TabButton)TabButton).AddDevice(device);

            ((GenTestProject2.AllComponentsButtons.ButtonList)ButtonList).AddDevice(device);
        }

        public void RemoveDevice(BasicTriListWithSmartObject device)
        {
            Devices.Remove(device);
            ComponentMediator.UnHookSmartObjectEvents(device.SmartObjects[ControlJoinId]);

        ((GenTestProject2.AllComponentsButtons.TabButton)TabButton).RemoveDevice(device);

        ((GenTestProject2.AllComponentsButtons.ButtonList)ButtonList).RemoveDevice(device);
        }

        #endregion

        #region CH5 Contract

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Button_PressEvent;
        private void onButton_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Button_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }

        /// <inheritdoc/>
        public event EventHandler<UIEventArgs> Toggle_PressEvent;
        private void onToggle_Press(SmartObjectEventArgs eventArgs)
        {
            EventHandler<UIEventArgs> handler = Toggle_PressEvent;
            if (handler != null)
                handler(this, UIEventArgs.CreateEventArgs(eventArgs));
        }
        /// <inheritdoc/>
        public void Button_Selected(AllComponentsButtonsBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Button_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Button_Selected(bool digital)
        {
            Button_Selected((sig, component) => sig.BoolValue = digital);
        }
        /// <inheritdoc/>
        public void Toggle_Selected(AllComponentsButtonsBoolInputSigDelegate callback)
        {
            for (int index = 0; index < Devices.Count; index++)
            {
                callback(Devices[index].SmartObjects[ControlJoinId].BooleanInput[Joins.Booleans.Toggle_SelectedState], this);
            }
        }

        /// <inheritdoc/>
        public void Toggle_Selected(bool digital)
        {
            Toggle_Selected((sig, component) => sig.BoolValue = digital);
        }

        /// <summary>
        /// ComplexComponent TabButton
        /// </summary>
        public GenTestProject2.AllComponentsButtons.ITabButton TabButton { get; private set; }

        /// <summary>
        /// ComplexComponent ButtonList
        /// </summary>
        public GenTestProject2.AllComponentsButtons.IButtonList ButtonList { get; private set; }

        #endregion

        #region Overrides

        public override int GetHashCode()
        {
            return (int)ControlJoinId;
        }

        public override string ToString()
        {
            return string.Format("Contract: {0} Component: {1} HashCode: {2} {3}", "AllComponentsButtons", GetType().Name, GetHashCode(), UserObject != null ? "UserObject: " + UserObject : null);
        }

        #endregion

        #region IDisposable

        public bool IsDisposed { get; set; }

        public void Dispose()
        {
            if (IsDisposed)
                return;

            IsDisposed = true;

            Button_PressEvent = null;
            Toggle_PressEvent = null;
        }

        #endregion
    }
}
